### ISSUE TITLE
Running the CPP project

### ISSUE THREAD

**Issue by Morolis** [fanlumaster/FanyLazyvim#1]
May I ask if it's possible to add a CPP project that can be managed, built, compiled, run, and debugged using CMake or other tools? I noticed that your settings only include Python and Rust, but it doesn't seem like C++is available because I haven't configured it for a long time. Could you please help me add the configuration

**Comment by fanlusky** [comment]
Yes, of course. In fact, the reson why I didn't customize shortcuts for cpp is that I prefer to use shell scripts to do all of those repeatable works. For example, in Windows, I use PowerShell scripts to automate it. That would also be very convient with the help of shell autocplemention capabilities. If you want to have a try, please take a look at my another repo: https://github.com/fanlumaster/leetcode-records/tree/master/Cpp, with llaunch.ps1 inside the folder, just run it in the commandline, it will build, compile and run binary files according to CMakeLists.

**Comment by Morolis** [comment]
My system uses the arch Linux system, so I would choose the llaunch.sh file. However, how should I configure and use it so that it can display the results of running the cpp file

**Comment by fanlusky** [comment]
> My system uses the arch Linux system, so I would choose the llaunch.sh file. However, how should I configure and use it so that it can display the results of running the cpp file

Just substitute variables in CMakeLists's line which starts with `add_executable` with your own cpp files. Then you could just run the llaunch.sh with your shell, e.g. zsh or fish. The output of the program will display at the end of the printed messages on commandline. BTW, these shell scripts are already tested on my Arch latest version . If you encounter some unexpected situations, ensure that you have prepared all prerequisites, e.g. CMake, gcc or llvm/clang.

**Comment by Morolis** [comment]
So I would like to ask, do you need to include your llaunch. sh in each CPP project? Otherwise, how can the llaunch. sh script retrieve and view the CMakeLists.txt in the project directory to see if it exists?

**Comment by fanlusky** [comment]
> So I would like to ask, do you need to include your llaunch. sh in each CPP project? Otherwise, how can the llaunch. sh script retrieve and view the CMakeLists.txt in the project directory to see if it exists?

You said it. However, there are also some other solutions to simplify this, for example, to maintain a project template repo on github, so we could reuse it when creating new projects next time.

**Comment by Morolis** [comment]
I can add your contact information (WeChat or QQ). It's a bit troublesome here. I just joined Neovim and would like to ask you some questions

**Comment by fanlusky** [comment]
> I can add your contact information (WeChat or QQ). It's a bit troublesome here. I just joined Neovim and would like to ask you some questions

Feel free to contact me by QQ, while telegram is better. You could find some of my contact infos on my GitHub profile or blog About page.
